FROM python:slim-buster

RUN apt update -y &&  apt install -y build-essential make git

ADD tb /tb/
ADD tests /tests/

RUN cd tb && make install
RUN pip3 install -r tests/requirements.txt

WORKDIR /tests

CMD ["make", "test"]